### PR TITLE
WebP support

### PR DESCRIPTION
**Pull request by shawngao5**
Usage: ./crosswalk-app build release --android-webp="80 80 100"
First number, quality of jpeg file. (0 - 100).
Second number, quality of png file. (0 - 100).
Third number, quality of png file alpha data. (0 - 100).

BUG=XWALK-3829

### CODE REVIEW

**Comment by r0b5t4** [comment]
@shawngao5 many thanks for your work. Before we go into a detailed review, what do you think about shipping the webp library, instead of downloading it. That would make the code much simpler. Did you investigate this option?

**Comment by shawngao5** [comment]
@r0b5t4 @halton If so, we should ship binaries for different platform, mac, win and linux, meanwhile, for different arch, x86 and x64. At least 5 files will be included. And maybe it also should be reviewed by lawyer team.

**Comment by r0b5t4** [comment]
We should discuss it at least. CC @baleboy

**Comment by shawngao5** [comment]
@r0b5t4 updated

**Comment by r0b5t4** [comment]
Integrated, many thanks.

**Comment by halton** [comment]
@r0b5t4 could you let me know why this PR get closed instead of merging?

**Comment by r0b5t4** [comment]
@halton I have integrated it manually with a few tweaks: https://github.com/crosswalk-project/crosswalk-app-tools/commit/5c69ce6ef2b97f39adbc05a802fef4f4899e4700

**Pull request closed without merging**
