### PR TITLE
CI: update ant release used in the appveyor VM

### PR DESCRIPTION
**Pull request by baleboy**
Ant release 1.9.7 was published and 1.9.6 was removed. Need to find a more resilient way to handle this, but for now I'm patching it so that releases can continue.

### CODE REVIEW

**Comment by r0b5t4** [comment]
lgtm but are those quotes changes unrelated? (Feeling nasty today)

**Comment by baleboy** [comment]
I just noticed that they were used in the appveyor examples, but yeah, probably not related. I can remove them

**Comment by r0b5t4** [comment]
nah next time?

**Comment by baleboy** [comment]
ok *blush*

**Pull request merged**
